async function imageIsRelevant(url,input,pageContext){if(!process.env.OPENAI_API_KEY)return false;const model=process.env.OPENAI_IMAGE_MODEL||process.env.OPENAI_MODEL||'gpt-5-mini';const productTitle=String(input?.title||input?.name||'').trim();const category=String(input?.category||input?.productType||'').trim();const description=String(input?.description||input?.shortDescription||'').replace(/<[^>]+>/g,' ').slice(0,1200);const prompt=`Prüfe dieses Produktbild für Homestro extrem streng. Das Bild darf NUR freigegeben werden, wenn es das konkrete angeforderte Produkt zeigt. Produktname: ${productTitle}. Kategorie: ${category}. Produktbeschreibung: ${description}. Quellseite: ${pageContext}. WICHTIG: Gleiche oder ähnliche Wörter auf der Quellseite reichen NICHT. Dekorationen, andere Produkte, Varianten anderer Produkte, Zubehör, Banner, Logos, Empfehlungen und Produkte mit gleichem Namen aber anderem Produkttyp müssen ABGELEHNT werden. Wenn du unsicher bist, ABLEHNEN. Antworte ausschließlich JSON: {"relevant":true/false,"confidence":0-1}`;try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+process.env.OPENAI_API_KEY},body:JSON.stringify({model,input:[{role:'user',content:[{type:'input_text',text:prompt},{type:'input_image',image_url:url,detail:'low'}]}],max_output_tokens:120})});const raw=await r.text();let d={};try{d=JSON.parse(raw);}catch(e){console.error('IMAGE VALIDATION NONJSON',r.status,raw.slice(0,160));return false;}if(!r.ok)return false;const out=cleanJson(d.output_text||d.output?.flatMap(x=>x.content||[]).map(x=>x.text||'').join('')||'{}');return out.relevant===true&&Number(out.confidence)>=0.85;}catch{return false;}}
async function imageIsRelevant(url,input,pageContext){
 if(!process.env.OPENAI_API_KEY)return false;
 const model=process.env.OPENAI_IMAGE_MODEL||process.env.OPENAI_MODEL||'gpt-5-mini';
 const prompt='Prüfe dieses konkrete Produktbild für Homestro extrem streng. Freigabe NUR wenn exakt das Produkt aus dem Produktnamen/der Beschreibung gezeigt wird und das Bild für einen deutschen Online-Shop geeignet ist. ABLEHNEN bei anderem Produkt, Zubehör statt Hauptprodukt, Banner, Logo, Wasserzeichen, Verpackung als Hauptmotiv, chinesischen/japanischen/koreanischen Schriftzeichen, fremdsprachigem Werbetext, irreführenden Angaben, starker Unschärfe oder schlechter Qualität. Wenn du unsicher bist, ABLEHNEN. Produkt: '+String(input?.title||'')+'. Kategorie: '+String(input?.category||input?.productType||'')+'. Beschreibung: '+homestroPlain(input?.description||'').slice(0,1500)+'. Quellkontext: '+String(pageContext||'').slice(0,3000)+'. Antworte nur JSON {"relevant":true/false,"confidence":0-1,"hasForeignText":true/false,"lowQuality":true/false}.';
 try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+process.env.OPENAI_API_KEY},body:JSON.stringify({model,input:[{role:'user',content:[{type:'input_text',text:prompt},{type:'input_image',image_url:url,detail:'high'}]}],max_output_tokens:180})});const raw=await r.text();const d=JSON.parse(raw);if(!r.ok)return false;const out=cleanJson(d.output_text||d.output?.flatMap(x=>x.content||[]).map(x=>x.text||'').join('')||'{}');return out.relevant===true&&out.hasForeignText!==true&&out.lowQuality!==true&&Number(out.confidence)>=0.85;}catch{return false;}
}
app.get('/api/automation/status-public',(_q,res)=>res.json({ok:true,service:'homestro-catalog-autopilot',enabled:process.env.HOMESTRO_CATALOG_ENABLED!=='false',intervalMs:catalogInterval(),running:catalogState.running,lastRun:catalogState.lastRun,lastError:catalogState.lastError,totals:{created:catalogState.created,rejected:catalogState.rejected,failed:catalogState.failed}}));

