const express=require('express');
const cors=require('cors');
const crypto=require('crypto');
const app=express();
const PORT=Number(process.env.PORT||8080);
app.use(cors({origin:true}));
app.use(express.json({limit:'4mb'}));
function cfg(){const domain=String(process.env.SHOPIFY_STORE_DOMAIN||'').trim().replace(/^https?:\/\//,'').replace(/\/$/,'');return{domain,token:String(process.env.SHOPIFY_ACCESS_TOKEN||'').trim(),clientId:String(process.env.SHOPIFY_CLIENT_ID||'').trim(),clientSecret:String(process.env.SHOPIFY_CLIENT_SECRET||'').trim()};}
let cached={token:'',expires:0};
async function getClientToken(){const c=cfg();if(!c.domain)throw Object.assign(new Error('Shopify is not configured.'),{status:503});if(c.token)return c.token;if(!c.clientId||!c.clientSecret)throw Object.assign(new Error('Shopify credentials are not configured.'),{status:503});if(cached.token&&Date.now()<cached.expires-60000)return cached.token;const r=await fetch(`https://${c.domain}/admin/oauth/access_token`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client_id:c.clientId,client_secret:c.clientSecret,grant_type:'client_credentials'})});const d=await r.json();if(!r.ok||!d.access_token)throw Object.assign(new Error(d.error_description||d.error||'Shopify token request failed'),{status:502});cached={token:d.access_token,expires:Date.now()+Number(d.expires_in||86400)*1000};return cached.token;}
function b64(s){return Buffer.from(s,'base64url');}
function validateIdToken(token){const c=cfg();if(!token||!c.clientSecret)throw new Error('Missing Shopify ID token configuration');const p=token.split('.');if(p.length!==3)throw new Error('Invalid ID token');const[h,payload,sig]=p;const head=JSON.parse(b64(h)),body=JSON.parse(b64(payload));if(head.alg!=='HS256')throw new Error('Unsupported ID token algorithm');const expected=crypto.createHmac('sha256',c.clientSecret).update(`${h}.${payload}`).digest(),got=b64(sig);if(got.length!==expected.length||!crypto.timingSafeEqual(got,expected))throw new Error('Invalid ID token signature');const now=Math.floor(Date.now()/1000);if(body.exp<=now||(body.nbf&&body.nbf>now))throw new Error('Expired or not-yet-valid ID token');if(body.aud!==c.clientId)throw new Error('Invalid ID token audience');if(!body.dest)throw new Error('Missing ID token destination');return body;}
async function exchangeIdToken(idToken,payload){const c=cfg(),shop=new URL(payload.dest).hostname;const r=await fetch(`https://${shop}/admin/oauth/access_token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,grant_type:'urn:ietf:params:oauth:grant-type:token-exchange',subject_token:idToken,subject_token_type:'urn:shopify:params:oauth:token-type:id_token',requested_token_type:'urn:shopify:params:oauth:token-type:offline-access-token',expiring:'1'})});const d=await r.json();if(!r.ok||!d.access_token)throw Object.assign(new Error('Token exchange failed'),{status:r.status===400?401:502});return{token:d.access_token,shop};}
async function getRequestToken(req){const a=req.get('authorization')||'',id=a.startsWith('Bearer ')?a.slice(7):'';const payload=validateIdToken(id);return exchangeIdToken(id,payload);}
async function shopifyGraphQL(query,variables={},overrideToken){const c=cfg();if(!c.domain)throw Object.assign(new Error('Shopify is not configured.'),{status:503});const token=overrideToken||await getClientToken();const r=await fetch(`https://${c.domain}/admin/api/2026-07/graphql.json`,{method:'POST',headers:{'Content-Type':'application/json','X-Shopify-Access-Token':token},body:JSON.stringify({query,variables})});const d=await r.json();if(!r.ok||d.errors?.length)throw Object.assign(new Error(d.errors?.map(x=>x.message).join('; ')||`Shopify HTTP ${r.status}`),{status:502});return d.data;}
function apiKey(req,res,next){const k=process.env.HOMESTRO_API_KEY,a=req.get('authorization')||'';if(!k)return res.status(503).json({ok:false,error:'API key is not configured.'});if(a==='Bearer '+k)return next();return res.status(401).json({ok:false,error:'Unauthorized'});}
async function sidekick(req,res,next){try{req.sidekick=await getRequestToken(req);next();}catch(e){res.set('X-Shopify-Retry-Invalid-Session-Request','1');res.status(e.status||401).json({ok:false,error:e.message});}}
app.get('/',(_q,res)=>res.type('html').send('<!doctype html><html lang="de"><body><h1>Homestro AI Control</h1><p>Backend online</p><p>Neue Produkte bleiben DRAFT.</p></body></html>'));
app.get('/health',(_q,res)=>res.json({ok:true,service:'homestro-ai-api',timestamp:new Date().toISOString()}));
app.get('/api/status',apiKey,(_q,res)=>res.json({ok:true,service:'homestro-ai-api',shopifyConfigured:Boolean(cfg().domain),openaiConfigured:Boolean(process.env.OPENAI_API_KEY)}));
app.get('/api/shopify/connection',apiKey,async(_q,res)=>{try{const d=await shopifyGraphQL('{shop{name myshopifyDomain}}');res.json({ok:true,connected:true,shop:d.shop});}catch(e){res.status(e.status||502).json({ok:false,connected:false,error:e.message});}});
app.get('/api/shopify/products',apiKey,async(req,res)=>{try{const first=Math.min(Math.max(Number(req.query.limit)||20,1),50),q=String(req.query.query||'').trim();const d=await shopifyGraphQL('query($first:Int!,$query:String){products(first:$first,query:$query){nodes{id title handle status vendor productType tags totalInventory priceRangeV2{minVariantPrice{amount currencyCode}maxVariantPrice{amount currencyCode}}variants(first:100){nodes{id title price sku inventoryQuantity selectedOptions{name value}image{id url altText}}}media(first:50){nodes{mediaContentType alt{id}}}seo{title description}}pageInfo{hasNextPage endCursor}}}',{first,query:q||null});res.json({ok:true,...d.products});}catch(e){res.status(e.status||502).json({ok:false,error:e.message});}});
function rules(){return{maxCost:Number(process.env.MAX_PRODUCT_COST||10),minSellingPrice:Number(process.env.MIN_SELLING_PRICE||34.9),minRatio:Number(process.env.MIN_PRICE_COST_RATIO||3)};}
function validateProduct(cost,sellingPrice,ratio){const r=rules();return{valid:Number.isFinite(cost)&&Number.isFinite(sellingPrice)&&Number.isFinite(ratio)&&cost<=r.maxCost&&sellingPrice>=r.minSellingPrice&&ratio>=r.minRatio,product:{cost,sellingPrice,ratio},rules:r};}
app.post('/api/products/validate',apiKey,(req,res)=>{const cost=Number(req.body?.cost),sellingPrice=Number(req.body?.sellingPrice),ratio=Number(req.body?.ratio);if(![cost,sellingPrice,ratio].every(Number.isFinite))return res.status(400).json({ok:false,error:'cost, sellingPrice and ratio must be numbers.'});res.json({ok:true,...validateProduct(cost,sellingPrice,ratio)});});
function cleanJson(t){return JSON.parse(String(t||'').trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/i,'').trim());}
async function aiProduct(input){if(!process.env.OPENAI_API_KEY)throw Object.assign(new Error('OPENAI_API_KEY is not configured.'),{status:503});const model=process.env.OPENAI_MODEL||'gpt-5-mini';const system='Du bist der deutsche E-Commerce-Redakteur von Homestro.de. Erstelle hochwertige, ehrliche und verkaufsstarke Produktdaten auf Deutsch. Keine erfundenen technischen Daten, Zertifikate, Garantien, Lieferzeiten, Bewertungen oder Verkaufszahlen. Ausgabe ausschließlich als gültiges JSON mit title,description,shortDescription,bullets,seoTitle,seoDescription,handle,tags,category.';const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+process.env.OPENAI_API_KEY},body:JSON.stringify({model,input:[{role:'system',content:[{type:'input_text',text:system}]},{role:'user',content:[{type:'input_text',text:'Verarbeite dieses Produkt:\n'+JSON.stringify(input,null,2)}]}],max_output_tokens:1800})});const d=await r.json();if(!r.ok)throw Object.assign(new Error(d?.error?.message||'OpenAI request failed'),{status:502});const text=d.output_text||d.output?.flatMap(x=>x.content||[]).map(x=>x.text||'').join('')||'';return{model,product:cleanJson(text)};}
app.post('/api/ai/product',apiKey,async(req,res)=>{try{res.json({ok:true,...await aiProduct(req.body?.product||req.body)});}catch(e){res.status(e.status||502).json({ok:false,error:e.message});}});
function absoluteUrl(u,base){try{return new URL(u,base).href;}catch{return null;}}
async function discoverImages(input){const supplied=[...(Array.isArray(input?.image_urls)?input.image_urls:[]),...(Array.isArray(input?.imageUrls)?input.imageUrls:[])].filter(Boolean);let urls=supplied.map(String);const source=String(input?.source_url||input?.sourceUrl||'').trim();if(source){try{const r=await fetch(source,{headers:{'User-Agent':'Mozilla/5.0 (compatible; HomestroBot/1.0)'},redirect:'follow'});if(r.ok){const html=await r.text();const found=[];const metaRe=/<meta[^>]+(?:property|name)=["'](?:og:image|twitter:image)["'][^>]+content=["']([^"']+)["'][^>]*>/gi;let m;while((m=metaRe.exec(html))&&found.length<20)found.push(m[1]);const imgRe=/<img[^>]+(?:src|data-src|data-original)=["']([^"']+)["'][^>]*>/gi;while((m=imgRe.exec(html))&&found.length<30)found.push(m[1]);urls.push(...found.map(x=>absoluteUrl(x,source)).filter(Boolean));}}catch{}}return[...new Set(urls.filter(u=>/^https?:\/\//i.test(u)))].slice(0,20);}
async function addMedia(productId,input,title,token){const urls=await discoverImages(input);if(!urls.length)return{count:0,urls:[]};const media=urls.map(url=>({mediaContentType:'IMAGE',originalSource:url,alt:String(title||'Homestro Produkt')}));const d=await shopifyGraphQL('mutation($productId:ID!,$media:[CreateMediaInput!]!){productCreateMedia(productId:$productId,media:$media){media{mediaContentType status}mediaUserErrors{field message}}}',{productId,media},token);const errs=d.productCreateMedia.mediaUserErrors||[];if(errs.length)throw Object.assign(new Error('Shopify rejected product images.'),{status:400,details:errs});return{count:(d.productCreateMedia.media||[]).length,urls};}
async function setSeo(productId,seo,token){if(!seo?.title&&!seo?.description)return null;const input={id:productId,seo:{title:String(seo.title||'').slice(0,70),description:String(seo.description||'').slice(0,320)}};const d=await shopifyGraphQL('mutation($input:ProductInput!){productUpdate(input:$input){product{id seo{title description}}userErrors{field message}}}',{input},token);if(d.productUpdate.userErrors?.length)throw Object.assign(new Error('Shopify rejected SEO data.'),{status:400,details:d.productUpdate.userErrors});return d.productUpdate.product;}
async function setProductTags(productId,tags,token){const arr=Array.isArray(tags)?tags.map(String).filter(Boolean):[];if(!arr.length)return null;const d=await shopifyGraphQL('mutation($input:ProductInput!){productUpdate(input:$input){product{id tags}userErrors{field message}}}',{input:{id:productId,tags:arr}},token);if(d.productUpdate.userErrors?.length)throw Object.assign(new Error('Shopify rejected product tags.'),{status:400,details:d.productUpdate.userErrors});return d.productUpdate.product;}
async function setVariantPricing(productId,price,cost,token){if(!Number.isFinite(price)&&!Number.isFinite(cost))return null;const q='{product(id:"'+productId.replace(/"/g,'\\"')+'"){variants(first:1){nodes{id}}}}';const d0=await shopifyGraphQL(q,{},token),id=d0.product?.variants?.nodes?.[0]?.id;if(!id)return null;const variant={id};if(Number.isFinite(price))variant.price=String(price);if(Number.isFinite(cost))variant.inventoryItem={cost:Number(cost)};const d=await shopifyGraphQL('mutation($productId:ID!,$variants:[ProductVariantsBulkInput!]!){productVariantsBulkUpdate(productId:$productId,variants:$variants,allowPartialUpdates:false){product{id variants(first:1){nodes{id price inventoryItem{unitCost{amount currencyCode}}}}}userErrors{field message}}}',{productId,variants:[variant]},token);if(d.productVariantsBulkUpdate.userErrors?.length)throw Object.assign(new Error('Shopify rejected price/cost.'),{status:400,details:d.productVariantsBulkUpdate.userErrors});return d.productVariantsBulkUpdate.product;}
async function createDraft(input,token){if(!input?.title)throw Object.assign(new Error('Product title is required.'),{status:400});const cost=Number(input.cost),price=Number(input.selling_price??input.sellingPrice),ratio=cost>0&&Number.isFinite(price)?price/cost:NaN;if(Number.isFinite(cost)&&Number.isFinite(price)){const v=validateProduct(cost,price,ratio);if(!v.valid)throw Object.assign(new Error('Product fails Homestro rules.'),{status:400,details:v.rules});}const product={title:String(input.title).trim(),descriptionHtml:String(input.descriptionHtml||input.description||'').trim(),handle:input.handle?String(input.handle).trim():undefined,vendor:input.vendor?String(input.vendor).trim():'Homestro',productType:String(input.productType||input.category||'').trim()||undefined,status:'DRAFT'};const d=await shopifyGraphQL('mutation($product:ProductCreateInput!){productCreate(product:$product){product{id title handle status vendor productType}userErrors{field message}}}',{product},token);if(d.productCreate.userErrors?.length)throw Object.assign(new Error('Shopify rejected the product.'),{status:400,details:d.productCreate.userErrors});const created=d.productCreate.product;const media=await addMedia(created.id,input,created.title,token);const seo=await setSeo(created.id,{title:input.seoTitle,description:input.seoDescription},token);const tagged=await setProductTags(created.id,input.tags,token);const priced=await setVariantPricing(created.id,price,cost,token);return{...created,mediaCount:media.count,seo:seo?.seo||null,tags:tagged?.tags||input.tags||[],pricingApplied:Boolean(priced)};}
app.post('/api/shopify/products/draft',apiKey,async(req,res)=>{try{res.status(201).json({ok:true,product:await createDraft(req.body?.product||req.body),status:'DRAFT'});}catch(e){res.status(e.status||502).json({ok:false,error:e.message,userErrors:e.details});}});
async function updateVariants(productId,variants,token){const normalized=(Array.isArray(variants)?variants:[]).map(v=>({id:String(v.id||''),optionValues:(v.optionValues||[]).map(o=>({optionName:String(o.optionName||''),name:String(o.name||'')}))})).filter(v=>v.id&&v.optionValues.length&&v.optionValues.every(o=>o.optionName&&o.name));if(!productId||!normalized.length)throw Object.assign(new Error('productId and valid variants are required.'),{status:400});const d=await shopifyGraphQL('mutation($productId:ID!,$variants:[ProductVariantsBulkInput!]!){productVariantsBulkUpdate(productId:$productId,variants:$variants,allowPartialUpdates:false){product{id title options{id name optionValues{id name}}variants(first:100){nodes{id title selectedOptions{name value}image{id url altText}}}}userErrors{field message}}}',{productId,variants:normalized},token);if(d.productVariantsBulkUpdate.userErrors?.length)throw Object.assign(new Error('Shopify rejected the variant update.'),{status:400,details:d.productVariantsBulkUpdate.userErrors});return d.productVariantsBulkUpdate.product;}
app.post('/api/shopify/products/variants',apiKey,async(req,res)=>{try{res.json({ok:true,product:await updateVariants(String(req.body.productId||''),req.body.variants,await getClientToken())});}catch(e){res.status(e.status||502).json({ok:false,error:e.message,userErrors:e.details});}});
app.get('/sidekick/import-product',(_req,res)=>res.type('html').send(`<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="shopify-api-key" content="${String(process.env.SHOPIFY_CLIENT_ID||'')}"><script src="https://cdn.shopify.com/shopifycloud/app-bridge.js"></script><title>Homestro AI Control</title></head><body><h1>Homestro AI Control</h1><div id="status">Sidekick-Workflow bereit…</div><script>
const status=document.getElementById('status');async function call(path,body){const token=await shopify.idToken();const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d;}function register(){if(!shopify.tools?.register)return;shopify.tools.register('optimize_product',async input=>call('/api/sidekick/optimize',{product:input.product}));shopify.tools.register('validate_product',async input=>call('/api/sidekick/validate',input));shopify.tools.register('create_product_draft',async input=>call('/api/sidekick/create-draft',input));shopify.tools.register('update_variants',async input=>call('/api/sidekick/variants',input));}async function run(){try{register();const req=shopify.intents?.request?.value;if(!req){status.textContent='Homestro Sidekick bereit.';return;}const p=req.data||{};status.textContent='Homestro: Prüfung → Text → SEO → Bilder → Preis/Kosten → DRAFT…';const cost=Number(p.cost),price=Number(p.selling_price),ratio=cost>0?price/cost:0;const v=await call('/api/sidekick/validate',{cost,sellingPrice:price,ratio});if(!v.valid)throw new Error('Produkt erfüllt die Homestro Regeln nicht.');const ai=await call('/api/sidekick/optimize',{product:p});const prepared={...p,...ai.product,descriptionHtml:ai.product.description};const created=await call('/api/sidekick/create-draft',{product:prepared});status.textContent='Fertig: DRAFT mit '+(created.product.mediaCount||0)+' Bildern.';await shopify.intents.response.ok({id:created.product.id});}catch(e){status.textContent='Fehler: '+e.message;try{await shopify.intents.response.error(e.message);}catch{}}}window.addEventListener('load',run);</script></body></html>`));
app.post('/api/sidekick/optimize',sidekick,async(req,res)=>{try{res.json({ok:true,...await aiProduct(req.body?.product||{})});}catch(e){res.status(e.status||502).json({ok:false,error:e.message});}});
app.post('/api/sidekick/validate',sidekick,(req,res)=>{const cost=Number(req.body?.cost),sellingPrice=Number(req.body?.sellingPrice),ratio=Number(req.body?.ratio);if(![cost,sellingPrice,ratio].every(Number.isFinite))return res.status(400).json({ok:false,error:'cost, sellingPrice and ratio must be numbers.'});res.json({ok:true,...validateProduct(cost,sellingPrice,ratio)});});
app.post('/api/sidekick/create-draft',sidekick,async(req,res)=>{try{res.status(201).json({ok:true,product:await createDraft(req.body?.product||{},req.sidekick.token),status:'DRAFT'});}catch(e){res.status(e.status||502).json({ok:false,error:e.message,userErrors:e.details});}});
app.post('/api/sidekick/variants',sidekick,async(req,res)=>{try{res.json({ok:true,product:await updateVariants(String(req.body.productId||''),req.body.variants,req.sidekick.token)});}catch(e){res.status(e.status||502).json({ok:false,error:e.message,userErrors:e.details});}});
app.use((_req,res)=>res.status(404).json({ok:false,error:'Not found'}));
app.use((err,_req,res,_next)=>res.status(err.status||500).json({ok:false,error:err.message||'Internal server error'}));
app.listen(PORT,()=>console.log(`Homestro AI Control listening on ${PORT}`));
