import {randomBytes} from 'node:crypto';
export function registerReview(app) {
  app.get('/marketing-review',(_req,res)=>{
    const nonce=randomBytes(16).toString('base64');
    res.set('Cache-Control','no-store').set('Content-Security-Policy',`default-src 'self'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'; img-src 'self' https://cdn.shopify.com; media-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'`);
    res.type('html').send(`<!doctype html><html lang="cs"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Homestro – kontrola marketingu</title>
      <style nonce="${nonce}">body{font:16px system-ui;margin:0;background:#f7f7f1;color:#162d22}main{max-width:960px;margin:40px auto;padding:20px}article{background:white;border:1px solid #ddd;border-radius:12px;padding:20px;margin:16px 0}button,input,textarea{font:inherit;padding:10px;margin:6px 0}button{background:#f6d044;border:0;border-radius:6px;cursor:pointer}textarea{width:95%;height:250px}pre{white-space:pre-wrap}img{max-width:180px;margin:4px}video{max-width:280px}label{display:block}#error{color:#b21c1c}header{display:flex;gap:10px;flex-wrap:wrap}</style>
      <main><h1>Homestro · organický marketing</h1><p>Návrhy se zveřejní až po schválení a zapnutí publikování. Reklamní rozpočet: 0 €.</p>
      <header><input id="key" type="password" autocomplete="off" placeholder="Soukromý API klíč Homestro"><button id="load">Načíst návrhy</button></header><p>Klíč zůstává v této stránce, neukládá se do prohlížeče.</p><p id="error"></p><pre id="status"></pre><section id="posts"></section><h2>Produkty čekající na doplnění</h2><section id="pending"></section></main>
      <script nonce="${nonce}">
      const $=id=>document.getElementById(id),node=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
      async function api(path,method='GET',body){const r=await fetch('/api/marketing/v2/'+path,{method,headers:{Authorization:'Bearer '+$('key').value,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const b=await r.json();if(!r.ok)throw Error(b.error||'Požadavek se nepodařil');return b;}
      async function load(){try{$('error').textContent='';$('status').textContent=JSON.stringify(await api('status'),null,2);const posts=await api('posts');$('posts').replaceChildren();for(const p of posts){const a=node('article');a.append(node('h2',p.payload.title+' · '+p.channel),node('pre',p.payload.caption));for(const url of p.payload.imageURLs||[]){const i=node('img');i.src=url;a.append(i);}if(p.payload.videoURL){const v=node('video');v.src=p.payload.videoURL;v.controls=true;a.append(v);}const b=node('button','Schválit přesně tento příspěvek');b.onclick=async()=>{if(!confirm('Schválit příspěvek? Zapnutý worker jej potom může zveřejnit.'))return;try{await api('posts/'+p.id+'/approve','POST',{reviewer:'Homestro owner'});await load();}catch(e){$('error').textContent=e.message;}};a.append(b);$('posts').append(a);}
      const pending=await api('pending-products');$('pending').replaceChildren();for(const p of pending){const a=node('article');a.append(node('h3',p.document.title),node('pre',p.reasons.join(', ')));const input=node('textarea');const d=p.document;input.value=JSON.stringify({supplierReference:d.supplierReference,landedCost:d.landedCost,priceReviewed:d.priceReviewed,contentReviewed:d.contentReviewed,germanCopy:d.germanCopy,facts:d.facts,categoryKey:d.categoryKey,productType:d.productType,brand:d.brand,unbranded:d.unbranded},null,2);a.append(input,node('p','contentReviewed=true potvrzuje správnost německého textu. Potvrzení práv k médiím ani zvláštní štítek nejsou podmínkou publikace. Chybějící náklady nech null.'));const b=node('button','Uložit zkontrolované údaje');b.onclick=async()=>{try{await api('products/'+encodeURIComponent(p.id)+'/inputs','PUT',JSON.parse(input.value));await load();}catch(e){$('error').textContent=e.message;}};a.append(b);$('pending').append(a);}}
      catch(e){$('error').textContent=e.message;}}
      $('load').onclick=load;
      </script></html>`);
  });
}
